"""empty message

Revision ID: 742ab741cd34
Revises: 404ee539d784
Create Date: 2022-03-01 18:51:57.684533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '742ab741cd34'
down_revision = '404ee539d784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'mass')
    op.drop_column('planets', 'orbit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('orbit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('gravity', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
