"""empty message

Revision ID: a68487ec2f40
Revises: 5d7bcdf61dc6
Create Date: 2022-03-02 21:44:21.402228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a68487ec2f40'
down_revision = '5d7bcdf61dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('email_2', table_name='user')
    op.drop_table('user')
    op.drop_constraint('favorite_people_ibfk_2', 'favorite_people', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_people', 'users', ['user_id'], ['id'])
    op.drop_constraint('favorite_planets_ibfk_2', 'favorite_planets', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_planets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_planets', type_='foreignkey')
    op.create_foreign_key('favorite_planets_ibfk_2', 'favorite_planets', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'favorite_people', type_='foreignkey')
    op.create_foreign_key('favorite_people_ibfk_2', 'favorite_people', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='user_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email_2', 'user', ['email'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
